{% set name = "appligator" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/appligator-{{ version }}.tar.gz
  sha256: 0ee227d8b3a9b07f1d1af0033256cc8591704f0a85cd9c26aebf96838d3e93c9

build:
  entry_points:
    - appligator = appligator.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic
    - pyyaml
    - typer
    - gavicore >=0.0.7
    - procodile >=0.0.7

test:
  imports:
    - appligator
  commands:
    - pip check
    - appligator --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/appligator
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: An EO application bundler and transformer.
  description: |
    Eozilla 🦖 Appligator is tool that bundles your workflows so 
    they can be recognized and executed by specific 
    workflow orchestrators.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - forman
    - pont-us
