{% set name = "appligator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/appligator-{{ version }}.tar.gz
  sha256: 49d48d5c493ab68761a2e19e0c0dc6829e0dab664e0ee89a92f453f121820fcb

build:
  entry_points:
    - appligator = appligator.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic
    - pyyaml
    - typer
    - gavicore >=0.1.0
    - procodile >=0.1.0

test:
  imports:
    - appligator
  commands:
    - pip check
    - appligator --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/appligator
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: An EO application bundler and transformer.
  description: |
    Eozilla 🦖 Appligator is tool that bundles your workflows so 
    they can be recognized and executed by specific 
    workflow orchestrators.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
