{% set name = "appligator" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/appligator-{{ version }}.tar.gz
  sha256: 852e3f4ad2230b1cbc067f60ea7e80be1fc3ed6af990b369a1fb364cef3354e4

build:
  entry_points:
    - appligator = appligator.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2
    - pydantic
    - pyyaml
    - tomli-w
    - typer >=0.26.0,<1
    - gavicore >=0.2.0
    - procodile >=0.2.0

test:
  imports:
    - appligator
  commands:
    - pip check
    - appligator --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/appligator
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: An EO application bundler and transformer.
  description: |
    Eozilla 🦖 Appligator is tool that bundles your workflows so 
    they can be recognized and executed by specific 
    workflow orchestrators.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
